### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/clojure#324]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/clojure/issues/315)
- [x] [Add key features](https://github.com/exercism/clojure/issues/316)
- [x] [Add tags](https://github.com/exercism/clojure/issues/317)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/clojure/issues/318)
- [x] [Update status of track](https://github.com/exercism/clojure/issues/322)
- [x] [Update status of Concept Exercises](https://github.com/exercism/clojure/issues/323)
- [x] [Pass linting checks](https://github.com/exercism/clojure/issues/319)
- [x] [Build Test Runner](https://github.com/exercism/clojure/issues/320)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/clojure/issues/321) (optional)
- [ ] [Add blurb to Concept Exercises](https://github.com/exercism/clojure/issues/342)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
